### PR TITLE
Fix a few typos and add a word here and there; Add Planned Features section to About page.

### PR DESCRIPTION
**Pull request by chrisspruck**
Fixed a few things, but nothing big.

### CODE REVIEW

**Review by ramsey — APPROVED** [review]

**Comment by chrisspruck** [comment]
@ramsey I talked with Matt about a couple more things to do in this branch/PR, so please hold on merging.

**Comment by ramsey** [comment]
I don’t havr permission to merge. I was just adding my approval. :smile:

**Comment by matthewtrask** [comment]
<3 @ramsey

**Comment by chrisspruck** [comment]
@matthewtrask Based on what we talked about, this is new ready to merge. FYI, I noticed Code Climate didn't run on this commit, like it did on the earlier ones.

**Pull request merged**
